scenario: financial_services_agent

baseline_tools:
  - dddd
  - ddddd

llm:
  provider: gemini
  model: gemini-2.0-flash
  api_key_file: API_Key/gemini_api_key

logging:
  base_dir: run/logs

runner:
  max_steps: 6

modes:
  normal:
    paths:
      system_prompt: scenarios/financial_services_agent/system.txt
      tasks: scenarios/financial_services_agent/tasks_benign.jsonl
      tools: scenarios/financial_services_agent/normal_tools.json

  attack:
    paths:
      system_prompt: scenarios/financial_services_agent/system.txt
      tasks: scenarios/financial_services_agent/tasks_attack.jsonl
      tools: scenarios/financial_services_agent/attack_tools.json
