scenario: system_admin_agent

# ✅ normal에서도 항상 열어둘 "정상 도구 2개"
baseline_tools:
  - sys_monitor
  - update_manager

llm:
  provider: gemini
  model: gemini-2.0-flash
  api_key_file: API_Key/gemini_api_key

logging:
  base_dir: run/logs

runner:
  max_steps: 6

modes:
  normal:
    paths:
      system_prompt: scenarios/system_admin_agent/system.txt
      tasks: scenarios/system_admin_agent/tasks_benign.jsonl
      tools: scenarios/system_admin_agent/normal_tools.json

  attack:
    paths:
      system_prompt: scenarios/system_admin_agent/system.txt
      tasks: scenarios/system_admin_agent/tasks_attack.jsonl
      tools: scenarios/system_admin_agent/attack_tools.json
